### ISSUE TITLE
Add crossingtheruby.com to RSS feeds

### ISSUE THREAD

**Issue by amitaibu** [Gizra/planet-elm#14]
http://crossingtheruby.com/elm.rss

cc @pootsbook

**Comment by amitaibu** [comment]
Done, welcome to Planet Elm :)

![planet_elm](https://cloud.githubusercontent.com/assets/125707/11092075/ffeeea24-8888-11e5-85c3-e173b5b065f0.jpg)

**Comment by pootsbook** [comment]
Thanks @amitaibu, hopefully I can keep the momentum up :smile:

**Comment by amitaibu** [comment]
:+1: yeah, your daily post is pretty great :)

**Comment by pootsbook** [comment]
Elm has been a lightning rod for creativity! The only downside to writing about Elm is that I’m not writing Elm :wink:
