### ISSUE TITLE
the "Continue reading ..." links consistently end with an extraneous "/"

### ISSUE THREAD

**Issue by amitaibu** [Gizra/planet-elm#20]

**Comment by amitaibu** [comment]
This seems to be a problem with the link created by the blog itself.

@pootsbook can you check this please - maybe the Jekyll recipe should be updated, as in your case your urls have the `file-name.html` format, where in Gizra for exmaple we have the `post-name/index.html` format.

**Comment by pootsbook** [comment]
I've had a go at fixing in pootsbook/pootsbook.github.io@4113093ab54799441a0e094d5af3bbc492a7705b. Thanks for the heads up.

EDIT: fix commit link

**Comment by amitaibu** [comment]
Done - Re-imported items
