### ISSUE TITLE
Publication date is broken

### ISSUE THREAD

**Issue by doppioslash** [Gizra/planet-elm#24]
```
<item>
    <title>Elm Script?</title>
    <link>http://crossingtheruby.com/2015/11/09/elm-script.html</link>

  <pubDate>&lt;a href=&quot;/node/11&quot;&gt;crossingtheruby.com&lt;/a&gt;</pubDate> <----

  <guid isPermaLink="false">http://crossingtheruby.com/2015/11/09/elm-script</guid>
  </item>
```

**Comment by amitaibu** [comment]
Thanks, I definitely need to add tests for that :/

Let's first quickly fix it...

**Comment by amitaibu** [comment]
Deployed to live. Thanks again for the bug report :)

<img width="581" alt="https___live-planet-elm_pantheon_io_feeds_xml" src="https://cloud.githubusercontent.com/assets/125707/11130441/bf73781a-898d-11e5-80df-b045df88e0b6.png">

**Comment by doppioslash** [comment]
That was quick :)
But I have another request, unfortunately the library I'm using cannot parse that date format: https://tonicdev.com/doppioslash/invaliddate

Could you use this kind of format: "Thu, 12 Nov 2015 21:55:50 +0000" ?

**Comment by amitaibu** [comment]
Drupal makes it so easy to change it ;)

<img width="771" alt="feed_items__content____planetelm" src="https://cloud.githubusercontent.com/assets/125707/11142048/44840d7a-89f3-11e5-89c5-f65e77f76511.png">

Results with `<pubDate>Thu, 05 Nov 2015 00:00:00 +0200</pubDate>`

Deplyed to LIVE
