### ISSUE TITLE
Add LambdaCat to RSS feeds

### ISSUE THREAD

**Issue by doppioslash** [Gizra/planet-elm#26]
Hello, 
can you add my site? 
Feed at http://www.lambdacat.com/tag/elm/rss/

**Comment by amitaibu** [comment]
Sure, but lets give you a user on Planet elm so you can do it yourself :) Can you please send me your email to amitai at gizra.com

**Comment by doppioslash** [comment]
@amitaibu email sent :)

**Comment by amitaibu** [comment]
You should get an email about your user.

Then you can go to https://live-planet-elm.pantheon.io/node/add/feed and add your feed. 

<img width="484" alt="create_feed___planet_elm" src="https://cloud.githubusercontent.com/assets/125707/11145313/d3aa1d32-8a0c-11e5-8734-dc71ff22b30d.png">

If you have any problem let me know. If it worked, you can close the issue ;)

**Comment by amitaibu** [comment]
@doppioslash I saw you added you feeds. I Hope Drupal was nice to you ;)

btw, if you decide to provide the RSS as teaser, I believe you should have the permissions to delete and re-import your feeds

<img width="628" alt="lambdacat___planet_elm" src="https://cloud.githubusercontent.com/assets/125707/11157613/207bc234-8a5b-11e5-8b71-cabfa238c804.png">

Can this be closed?

**Comment by doppioslash** [comment]
It was :) 
I do have the permissions yes. I use Ghost and it doesn't have any RSS customisation, which is annoying. A `<description>` is included but Drupal is using the `<content>`. 

I'll have to find a way to modify the RSS feed outside of Ghost.

**Comment by amitaibu** [comment]
http://import.jekyllrb.com/docs/ghost/ :wink:
