### ISSUE TITLE
Add blog post series

### ISSUE THREAD

**Issue by basti1302** [Gizra/planet-elm#27]
As discussed on Twitter today, I'll humbly submit the following feed:

https://blog.codecentric.de/en/feed?tag=Elm

There's not too much there yet but I'll publish a new episode each week.

**Comment by amitaibu** [comment]
Thanks, done!

![planet_elm](https://cloud.githubusercontent.com/assets/125707/11180950/21eeee8a-8c67-11e5-8d36-07f217c5dc13.jpg)

**Comment by basti1302** [comment]
Thanks! <3
