### ISSUE TITLE
Add rundis.github.com/blog feed

### ISSUE THREAD

**Issue by rundis** [Gizra/planet-elm#28]
Hi !

I've managed to create an elm only feed for my blog. Feel free to add it to planet-elm if it meets the criteria.
http://rundis.github.io/blog/elmfeed.xml

Let me know if there is anything more I need to do !

cheers
Magnus

**Comment by amitaibu** [comment]
Great!

I've tested the feed on a dev site, and I see the images are relative. Can this be fixed to be absolute?

![planet_elm-2](https://cloud.githubusercontent.com/assets/125707/11181560/a64c1b5e-8c6b-11e5-9494-b02ba673d370.jpg)

**Comment by rundis** [comment]
I've fixed in manually for that particular post. Hoping I'll find a generic mechanism for my blog engine for future posts...

tx for quick response (and qa !)

**Comment by amitaibu** [comment]
Looking good, added! :)

![articles_from_rundis___planet_elm](https://cloud.githubusercontent.com/assets/125707/11182102/ced48156-8c70-11e5-92ad-8ab32bffcc23.jpg)

**Comment by amitaibu** [comment]
(feeds will appear shortly on the live site, as page is cached with Varnish)

**Comment by rundis** [comment]
cheers!

I'll look into howto extract a summary rather than just dumping the whole post.

**Comment by amitaibu** [comment]
Great, let me know, so I'll re-import the feeds once you've done it.
