### ISSUE TITLE
Request to have RSS feed added to Planet Elm

### ISSUE THREAD

**Issue by brendan-jefferis** [Gizra/planet-elm#29]
I've just started a blog about Elm, with a focus on using Elm in a production environment. Content will be mainly tips and tutorials.

[Blog](http://bjefferis.svbtle.com/)

[RSS feed](http://bjefferis.svbtle.com/feed)

Feed has [passed validation](http://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fbjefferis.svbtle.com%2Ffeed)

**Comment by amitaibu** [comment]
Done, thanks!

![planet_elm](https://cloud.githubusercontent.com/assets/125707/11322999/cf2d434a-910c-11e5-9ea1-d21e82bfd9da.jpg)

**Comment by brendan-jefferis** [comment]
Awesome, thanks :)

**Comment by amitaibu** [comment]
@brendan-jefferis you blog no longer seems to be available, can you please confirm this.

**Comment by brendan-jefferis** [comment]
Updated URL http://boonofcode.svbtle.com/feed

On Mon, Nov 23, 2015 at 7:53 AM, Amitai Burstein notifications@github.com
wrote:

> @brendan-jefferis https://github.com/brendan-jefferis you blog no
> longer seems to be available, can you please confirm this.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Gizra/planet-elm/issues/29#issuecomment-158789272.

## 

Brendan Jefferis
+64 2 302 4062
brendan.jefferis@gmail.com

**Comment by amitaibu** [comment]
Re-imported.

**Comment by brendan-jefferis** [comment]
Damn, that was super fast. Nice work!

On Mon, Nov 23, 2015 at 7:59 AM, Amitai Burstein notifications@github.com
wrote:

> Reopened #29 https://github.com/Gizra/planet-elm/issues/29.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Gizra/planet-elm/issues/29#event-471552590.

## 

Brendan Jefferis
+64 2 302 4062
brendan.jefferis@gmail.com

**Comment by amitaibu** [comment]
Don't thank me, thank Drupal ;)
