### ISSUE TITLE
Add FullyForged's elm feed

### ISSUE THREAD

**Issue by cloud8421** [Gizra/planet-elm#33]
Hello, the feed is available here:

http://www.fullyforged.com/feed.elm.xml

This is an example post:

http://www.fullyforged.com/2016/01/21/phoenix-and-elm-tracking-the-connection-status.html

For context: FullyForged is a consultancy based in London, focusing on software development and training around Elixir, Javascript and now Elm.

Thanks!

**Comment by amitaibu** [comment]
Welcome to Planet Elm :)

![planet_elm](https://cloud.githubusercontent.com/assets/125707/12518799/5b76ffe2-c143-11e5-83fe-01290d2f53fa.jpg)

(might take a few minutes for Varnish cache to show the post)
