### ISSUE TITLE
Add Trouble (::)entrating

### ISSUE THREAD

**Issue by lukewestby** [Gizra/planet-elm#35]
Hi folks!

I've got two elm-related posts and want to throw my feed into the ring! I saw in the guidelines that press releases aren't acceptable content, and I wasn't sure if that applied to announcements of open source pacakges. All of the posts I write about my open-source releases will not just be announcements, but explanations of why the changes that went in were included and what problems the solve. Anyway, here is the feed link and html link for your review!

http://lukewestby.com/tags/elm/
http://lukewestby.com/tags/elm/index.xml

**Comment by amitaibu** [comment]
Happy to have you around! :)

(it might take a few minutes for varnish to show you the new content)

![planet_elm-2](https://cloud.githubusercontent.com/assets/125707/13389003/741c6896-decd-11e5-94fd-f552310d5d7a.jpg)

**Comment by lukewestby** [comment]
:tada: thanks amitai!

**Comment by amitaibu** [comment]
:+1:

**Comment by amitaibu** [comment]
Thanks for elm-http-extra ;)
