### ISSUE TITLE
Add my elm articles feed

### ISSUE THREAD

**Issue by dennisreimann** [Gizra/planet-elm#38]
Hey there, I've created a separate feed for the Elm related articles on my blog, which you can find here: https://dennisreimann.de/articles/elm.xml

Please add this to the planet whenever you find the time to do so :)

**Comment by amitaibu** [comment]
Thanks. Done (might take a few minutes for Varnish cache to show the new items)

![planet_elm](https://cloud.githubusercontent.com/assets/125707/20193149/67cd69e6-a795-11e6-853c-633565ccecaa.jpg)

**Comment by dennisreimann** [comment]
Great @amitaibu! Thanks a lot :cake:
