### ISSUE TITLE
Here's my feed!

### ISSUE THREAD

**Issue by BrianHicks** [Gizra/planet-elm#39]
Hi, could you add me to the planet, please?

**Elm-specific feed URL:** https://www.brianthicks.com/tags/elm/index.xml. It passes validation and trims to a summary.
**Name:** Brian Hicks

I've got a bunch of posts you can look at to validate. Probably easiest to just point your browser at brianthicks.com :)

**Comment by amitaibu** [comment]
Awesome stuff. Added

![planet_elm](https://cloud.githubusercontent.com/assets/125707/21174453/e3ed5684-c1e5-11e6-888e-82568f6f86f3.jpg)

**Comment by BrianHicks** [comment]
Yay, thanks!
