### ISSUE TITLE
Request to add my feed

### ISSUE THREAD

**Issue by wintvelt** [Gizra/planet-elm#40]
For some time, I post regularly (trying to keep up once per week) over on Medium. 
All my posts are elm related, and I believe that (at least from content point of view) they meet your requirements.
Here's my feed: https://medium.com/feed/@wintvelt

If you want to include it in Planet Elm, that would be awesome.  You can simply use my nickname "wintvelt"

Thanks for maintaining this great elm feed!

**Comment by amitaibu** [comment]
Hi!

When testing (it's not on the live site) seems that the RSS feed contains also comments, which are imported as posts. Can youplease filter those out.

![articles_from_wintvelt___planet_elm](https://cloud.githubusercontent.com/assets/125707/21458821/4b1abb9a-c942-11e6-9db4-da140e08241b.jpg)

**Comment by wintvelt** [comment]
Hmm didn't realize that. We don't want the responses of course. Will look into it and see if I can filter those out..

**Comment by wintvelt** [comment]
OK, I turned it into a (still modest) publication on elm. 
https://medium.com/feed/elm-shorts
Hope this is better..

**Comment by amitaibu** [comment]
Looks good. It should appear in a few minutes in the live site

![planet_elm](https://cloud.githubusercontent.com/assets/125707/21460596/dae1f4fe-c952-11e6-96cd-624d45b75199.jpg)

Thanks!
