### ISSUE TITLE
Add https://blog.ilias.xyz

### ISSUE THREAD

**Issue by zwilias** [Gizra/planet-elm#43]
At @BrianHicks' suggestion, I propose adding my blog to this aggregation. I've written a few things about Elm, and intend to keep on writing in the future.

Feed URL: https://blog.ilias.xyz/feed
(note that this is a Medium blog, so I don't have a whole lot of control as far as the feed is concerned..)

**Comment by amitaibu** [comment]
Done. This will appear in the site in a couple of minutes when Varnish is cleared.

![articles_from_ilias_van_peer___planet_elm](https://cloud.githubusercontent.com/assets/125707/25574406/c740e6ee-2e56-11e7-9020-3351dc6ce021.jpg)

Thanks :)

**Comment by zwilias** [comment]
Awesome, thanks!
